import pdb

import repositories.city_repository as city_repository
import repositories.country_repository as country_repository
import repositories.destination_repository as destination_repository
import repositories.user_repository as user_repository
from models.city import City
from models.country import Country
from models.destination import Destination
from models.user import User

# user_1 = User('Giuliano', 'Derosas', 'Bali')
# user_repository.save(user_1)

# country_1 = Country('Thailand')
# country_repository.save(country_1)

# city_1 = City(country_1, 'Bangkok')
# city_repository.save(city_1)

# destination_1 = Destination(user_1, country_1, city_1, 'Street Food')
# destination_repository.save(destination_1)

for country in countries_list:
    country_repository.save(country)

countries_list =[
    country_1 = Country("Afghanistan")
    country_2 = Country("Albania")
    country_3 = Country("Algeria")
    country_4 = Country("Andorra")
    country_5 = Country("Angola")
    country_6 = Country("Antigua and Barbuda")
    country_7 = Country("Argentina")
    country_8 = Country("Armenia")
    country_9 = Country("Australia")
    country_10 = Country("Austria")
    country_11 = Country("Azerbaijan")
    country_12 = Country("Bahamas")
    country_13 = Country("Bahrain")
    country_14 = Country("Bangladesh")
    country_15 = Country("Barbados")
    country_16 = Country("Belarus")
    country_17 = Country("Belgium")
    country_18 = Country("Belize")
    country_19 = Country("Benin")
    country_20 = Country("Bhutan")
    country_21 = Country("Bolivia")
    country_22 = Country("Bosnia and Herzegovina")
    country_23 = Country("Botswana")
    country_24 = Country("Brazil")
    country_25 = Country("Brunei Darussalam")
    country_26 = Country("Bulgaria")
    country_27 = Country("Burkina Faso")
    country_28 = Country("Burundi")
    country_29 = Country("Cabo Verde")
    country_30 = Country("Cambodia")
    country_31 = Country("Cameroon")
    country_32 = Country("Canada")
    country_33 = Country("Central African Republic")
    country_34 = Country("Chad")
    country_35 = Country("Chile")
    country_36 = Country("China")
    country_37 = Country("Colombia")
    country_38 = Country("Comoros")
    country_39 = Country("Congo")
    country_40 = Country("Congo, Democratic Republic of the")
    country_41 = Country("Costa Rica")
    country_42 = Country("Côte d'Ivoire")
    country_43 = Country("Croatia")
    country_44 = Country("Cuba")
    country_45 = Country("Cyprus")
    country_46 = Country("Czechia")
    country_47 = Country("Denmark")
    country_48 = Country("Djibouti")
    country_49 = Country("Dominica")
    country_50 = Country("Dominican Republic")
    country_51 = Country("Ecuador")
    country_52 = Country("Egypt")
    country_53 = Country("El Salvador")
    country_54 = Country("Equatorial Guinea")
    country_55 = Country("Eritrea")
    country_56 = Country("Estonia")
    country_57 = Country("Eswatini")
    country_58 = Country("Ethiopia")
    country_59 = Country("Fiji")
    country_60 = Country("Finland")
    country_61 = Country("France")
    country_62 = Country("Gabon")
    country_63 = Country("Gambia")
    country_64 = Country("Georgia")
    country_65 = Country("Germany")
    country_66 = Country("Ghana")
    country_67 = Country("Greece")
    country_68 = Country("Grenada")
    country_69 = Country("Guatemala")
    country_70 = Country("Guinea")
    country_71 = Country("Guinea-Bissau")
    country_72 = Country("Guyana")
    country_73 = Country("Haiti")
    country_74 = Country("Honduras")
    country_75 = Country("Hungary")
    country_76 = Country("Iceland")
    country_77 = Country("India")
    country_78 = Country("Indonesia")
    country_79 = Country("Iran (Islamic Republic of)")
    country_80 = Country("Iraq")
    country_81 = Country("Ireland")
    country_82 = Country("Israel")
    country_83 = Country("Italy")
    country_84 = Country("Jamaica")
    country_85 = Country("Japan")
    country_86 = Country("Jordan")
    country_87 = Country("Kazakhstan")
    country_88 = Country("Kenya")
    country_89 = Country("Kiribati")
    country_90 = Country("Korea (Democratic People's Republic of)")
    country_91 = Country("Korea, Republic of")
    country_92 = Country("Kuwait")
    country_93 = Country("Kyrgyzstan")
    country_94 = Country("Lao People's Democratic Republic")
    country_95 = Country("Latvia")
    country_96 = Country("Lebanon")
    country_97 = Country("Lesotho")
    country_98 = Country("Liberia")
    country_99 = Country("Libya")
    country_100 = Country("Liechtenstein")
    country_101 = Country("Lithuania")
    country_102 = Country("Luxembourg")
    country_103 = Country("Madagascar")
    country_104 = Country("Malawi")
    country_105 = Country("Malaysia")
    country_106 = Country("Maldives")
    country_107 = Country("Mali")
    country_108 = Country("Malta")
    country_109 = Country("Marshall Islands")
    country_110 = Country("Mauritania")
    country_111 = Country("Mauritius")
    country_112 = Country("Mexico")
    country_113 = Country("Micronesia (Federated States of)")
    country_114 = Country("Moldova, Republic of")
    country_115 = Country("Monaco")
    country_116 = Country("Mongolia")
    country_117 = Country("Montenegro")
    country_118 = Country("Morocco")
    country_119 = Country("Mozambique")
    country_120 = Country("Myanmar")
    country_121 = Country("Namibia")
    country_122 = Country("Nauru")
    country_123 = Country("Nepal")
    country_124 = Country("Netherlands")
    country_125 = Country("New Zealand")
    country_126 = Country("Nicaragua")
    country_127 = Country("Niger")
    country_128 = Country("Nigeria")
    country_129 = Country("North Macedonia")
    country_130 = Country("Norway")
    country_131 = Country("Oman")
    country_132 = Country("Pakistan")
    country_133 = Country("Palau")
    country_134 = Country("Panama")
    country_135 = Country("Papua New Guinea")
    country_136 = Country("Paraguay")
    country_137 = Country("Peru")
    country_138 = Country("Philippines")
    country_139 = Country("Poland")
    country_140 = Country("Portugal")
    country_141 = Country("Qatar")
    country_142 = Country("Romania")
    country_143 = Country("Russian Federation")
    country_144 = Country("Rwanda")
    country_145 = Country("Saint Kitts and Nevis")
    country_146 = Country("Saint Lucia")
    country_147 = Country("Saint Vincent and the Grenadines")
    country_148 = Country("Samoa")
    country_149 = Country("San Marino")
    country_150 = Country("Sao Tome and Principe")
    country_151 = Country("Saudi Arabia")
    country_152 = Country("Senegal")
    country_153 = Country("Serbia")
    country_154 = Country("Seychelles")
    country_155 = Country("Sierra Leone")
    country_156 = Country("Singapore")
    country_157 = Country("Slovakia")
    country_158 = Country("Slovenia")
    country_159 = Country("Solomon Islands")
    country_160 = Country("Somalia")
    country_161 = Country("South Africa")
    country_162 = Country("South Sudan")
    country_163 = Country("Spain")
    country_164 = Country("Sri Lanka")
    country_165 = Country("Sudan")
    country_166 = Country("Suriname")
    country_167 = Country("Sweden")
    country_168 = Country("Switzerland")
    country_169 = Country("Syrian Arab Republic")
    country_170 = Country("Tajikistan")
    country_171 = Country("Tanzania, United Republic of")
    country_172 = Country("Thailand")
    country_173 = Country("Timor-Leste")
    country_174 = Country("Togo")
    country_175 = Country("Tonga")
    country_176 = Country("Trinidad and Tobago")
    country_177 = Country("Tunisia")
    country_178 = Country("Turkey")
    country_179 = Country("Turkmenistan")
    country_180 = Country("Tuvalu")
    country_181 = Country("Uganda")
    country_182 = Country("Ukraine")
    country_183 = Country("United Arab Emirates")
    country_184 = Country("United Kingdom of Great Britain and Northern Ireland")
    country_185 = Country("United States of America")
    country_186 = Country("Uruguay")
    country_187 = Country("Uzbekistan")
    country_188 = Country("Vanuatu")
    country_189 = Country("Venezuela (Bolivarian Republic of)")
    country_190 = Country("Viet Nam")
    country_191 = Country("Yemen")
    country_192 = Country("Zambia")
    country_193 = Country("Zimbabwe")
]

pdb.set_trace()

